### ISSUE TITLE
Build Environment is Not Consistent Across Builds

### ISSUE THREAD

**Issue by DeusFerrariis** [Agorist-Digital/harmonic-gallery-collective#9]
After reproducing development environment locally issues arise getting project to run. Build did not have postcss configured and now has the following issue:

```
[plugin:astro:build] Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at /home/will/Github/harmonic-gallery-collective/src/components/NavMenu.astro?astro&type=style&lang.css:26:9
    at Function.keys (<anonymous>)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:22:42)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/home/will/Github/harmonic-gallery-collective/node_modules/autoprefixer/lib/prefixer.js:38:17
```

Suggested fix is to reconfigure build environment in a reproducible manner.

**Comment by DeusFerrariis** [comment]
Project has been switched to SvelteKit see https://github.com/Agorist-Digital/harmonic-gallery-collective/commit/78ad2ec63ad73d273568671b2fd79621ae54a04c.
